---
title: "assessment 1.1"
author: "Timothy To"
date: "8/16/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(tidyverse)
library(skimr)
library(janitor)
library(dplyr)
library(reshape)
library(tidyr)
library(knitr)
library(lubridate)
library(scales)
library(formattable)
fastfood<-read.csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv')
```

# **RMarkdown editing**
**R Markdown is a file format for making dynamic documents with R. An R Markdown document is written in markdown (an easy-to-write plain text format) and contains chunks of embedded R code**

**__#Part 1__**

```{r}

head(fastfood,10)

knitr::kable(fastfood[1:10,1:5],"pipe")

fastfood%>%filter(calories>1000)

dont_eat_this<-fastfood%>%
select(restaurant,item,total_fat, total_carb)%>%
filter(total_fat>40, total_carb>80 )

fastfood%>%
  filter(restaurant=="Mcdonalds")
  
```

#**part 2**

```{r}
fastfood%>%skim()

fastfood%>%count(restaurant)


fastfood%>%group_by(restaurant)%>%summarise(calories=mean(calories))


fastfood %>% group_by(restaurant)  %>% mutate (average_calories = mean(calories)) %>% ungroup ()


fastfood%>%ggplot(aes(restaurant,total_fat))+geom_col()+theme_classic()

#A bar chart can show a distribution of data to do comparison of metric values across different subgroup. The reasons i choose bar chart rather than another graph, due to it is easier for us to do the comparison against each others. 

fastfood%>%group_by(restaurant) %>% mutate(max_total_fat = max(total_fat)) %>% ungroup()


fastfood%>%filter(restaurant=="Mcdonalds")%>%ggplot(aes(sugar,protein))+geom_point()


```

#**part 3**

```{r}
#18
restaurant=as.factor(fastfood$restaurant)
item=as.factor(fastfood$item)
salad=as.factor(fastfood$salad)
calories=as.factor(fastfood$calories)

#19
calories_type <- fastfood%>%
  mutate(calories_type=cut_number(calories,n=3,labels=c("low","medium","high")))
  calories_type%>%
  arrange(calories_type)


  
#20
  
calories_type%>%
ggplot(aes(x=calories, y=restaurant, colour=calories_type))+
  geom_line(sharp=13, size=3)+
  facet_wrap(~calories_type)+
  coord_cartesian()+
  theme_dark(base_size = 10)+
  labs(title = "Resturant's calories count")

#21

trans_fat_percent <- fastfood%>%
  mutate(trans_fat_percent = trans_fat/total_fat, trans_fat_percent=scales::percent(trans_fat_percent))

#22
trans_fat_percent%>%
 ggplot(aes(restaurant, trans_fat)) +
  geom_col(fill= "blue")+
  facet_wrap(~trans_fat)+
  coord_flip()+
  theme_bw(base_size = 11)+
  labs(title = "Trans fat in resturant")

#23 
fastfood%>%
  group_by(restaurant)%>%
  summarise(total_fat=mean(total_fat))

#24
fastfood%>%
ggplot(aes(x=restaurant, y=total_fat))+geom_col(fill="orange")+
  coord_cartesian()+
  theme(axis.text.x = element_text(angle = 30, hjust = 1))+
  theme_dark(base_size = 11)+
  labs(title="resturant and total fat")
  
 
  
  
  
                                          
  

```


